### ISSUE TITLE
Possible problem in Windows

### ISSUE THREAD

**Issue by HFOlivier** [Maarc/windup-as-a-service#1]
Hello,

I am currently trying to use this tool in a project. We followed the instructions and started a JBoss EAP 6.3 to run the tool. Once we try to upoad an ear on the Webside we get the following exception:
12:16:49,137 WARNING [FileUtil] (http-/127.0.0.1:8080-1) Caught an exception while trying to store file \tmp\winddrop\storage\pp.ear-0c72714be6dd68dea07692f49641e1e7adb62c690db567e68b91d15b11bb1de3-2015-01-07_12:16:49.uploaded (The filename, directory name, or volume label syntax is incorrect)
12:16:49,139 SEVERE [UploadService] (http-/127.0.0.1:8080-1) >>> uploadFile - This should not have happened: java.io.IOException: The filename, directory name, or volume label syntax is incorrect

We are thiking, that this might be a Windows problem with the length of the path. But first analysis showed a length less than the 260 characters recommendet. We also moved the uploaded Ear file to the lowest possible hierachy (just saved it to d:). The ear file is called "pp.ear". Are there any other restrictions for the toll we need to be aware of which might produce this error?

**Comment by Maarc** [comment]
Hi Olivier,

In deed it has not been built for Windows. I tested it on MacOs and RHEL, using Firefox and Chrome.

Thanks for you feedback!

best regards,

Marc
